// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtRiFO4qqFF436i4CtMonIzJrYByuoCsQ',
    appId: '1:1651885726:web:461f70d41cc5f543685d8f',
    messagingSenderId: '1651885726',
    projectId: 'weiss-db-7f516',
    authDomain: 'weiss-db-7f516.firebaseapp.com',
    storageBucket: 'weiss-db-7f516.appspot.com',
    measurementId: 'G-L6FB1CDESF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD_NDPSiVx4ruiMzhG5Yu5wmjtYGAxhCM',
    appId: '1:1651885726:android:4cefb20748f23b34685d8f',
    messagingSenderId: '1651885726',
    projectId: 'weiss-db-7f516',
    storageBucket: 'weiss-db-7f516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9G7_39WD6NZv1vRS0SIzm5o3inADpTiE',
    appId: '1:1651885726:ios:0a950899c96ab3a3685d8f',
    messagingSenderId: '1651885726',
    projectId: 'weiss-db-7f516',
    storageBucket: 'weiss-db-7f516.appspot.com',
    iosClientId: '1651885726-e10vfqmipc8apanc9ao488o3jbmv4o0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.weissApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9G7_39WD6NZv1vRS0SIzm5o3inADpTiE',
    appId: '1:1651885726:ios:0a950899c96ab3a3685d8f',
    messagingSenderId: '1651885726',
    projectId: 'weiss-db-7f516',
    storageBucket: 'weiss-db-7f516.appspot.com',
    iosClientId: '1651885726-e10vfqmipc8apanc9ao488o3jbmv4o0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.weissApp',
  );
}
